name: 'Sanity checks before merging PR'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push: 
    branches:
      -main

jobs:

  # Job 1: Simulating some sanity checks are done
  sanity-checks-to-the-built-files-before-merging: 
    name: Sanity Checks Before Merging 
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      TZ: Europe/Madrid  # Set the timezone to your local timezone
    steps: 
      - name: Simulating that some testings and checks are done
        run: |
          echo "Simulating that some testings and checks are done"
